### PR TITLE
Switch formatting to Eclipse defaults with 4-space indent.

### PR DESCRIPTION
**Pull request by dbwiddis**

### CODE REVIEW

**Comment by hazendaz** [comment]
If you can look at my PR first given this one will cause major merge conflicts and it would be much easier to do mine first then do this again.  I did pretty much bring in what was needed.  Just needs to rename a file and do the same thing again.

**Comment by dbwiddis** [comment]
Go ahead and do yours first, I'll re-sync and catch any changes in this PR.

**Comment by hazendaz** [comment]
ok - so best way to do this would be locally for you would be.  This assumes using your fork.

git reset --hard HEAD~1
git pull --rebase upstream master
Reapply your changes for causing the formatting and run the build.
then force push.  PR can stay open as it allows that.
git push origin +master

Then it should be good to pull in.  I'm signing off for the night.  ttyl

**Comment by dbwiddis** [comment]
I just re-synced, which apparently auto-closed this PR... oh well.  Let me try and tweak my eclipse to match the existing formatting!

**Comment by dbwiddis** [comment]
OK, changed tabs to spaces (4) and exported as format.xml.  Assuming build reads this file, we're good.

**Comment by dbwiddis** [comment]
Fixes #90

**Pull request merged**
