### PR TITLE
Fix pom spacing.

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by dbwiddis** [comment]
Did you see I had #66 waiting for review to fix this and a few other things? :)

**Comment by hazendaz** [comment]
Oops..my mistake.  I was going through all my git repos pushing things I've had out for the last few weeks.  I didn't look out for any pulls.  I will be back online in a couple of hours.  I'll review what you have.  If I caused a merge conflict I'll fix it. Sorry about that.


Sent by Outlook for Android





On Sun, Jul 12, 2015 at 1:14 PM -0700, "dbwiddis" <notifications@github.com> wrote:
Did you see I had #66 waiting for review to fix this and a few other things? :)

---

**Comment by hazendaz** [comment]
Ah and there was that other waffle...ball was in my court to review.  I'll perform a quick search after the PR just to be sure no more waffles around.  Thanks for getting release updates in there.


Sent by Outlook for Android





On Sun, Jul 12, 2015 at 1:27 PM -0700, <jeremylandis@hotmail.com> wrote:
Oops..my mistake.  I was going through all my git repos pushing things I've had out for the last few weeks.  I didn't look out for any pulls.  I will be back online in a couple of hours.  I'll review what you have.  If I caused a merge conflict I'll fix it. Sorry about that.


Sent by Outlook for Android





On Sun, Jul 12, 2015 at 1:14 PM -0700, "dbwiddis" <notifications@github.com> wrote:
Did you see I had #66 waiting for review to fix this and a few other things? :)

---

**Comment by dbwiddis** [comment]
Was hoping you would confirm the release update process as well. I put 
it together from your emails.

**Pull request merged**
