### PR TITLE
Battery Information

### PR DESCRIPTION
**Pull request by dbwiddis**
Submitted for review/discussion of API structure before continuing Linux and Windows ports.

Sample output: 
Power: InternalBattery-0 (Charging) @ 96.01%, 0:55 remaining.

### CODE REVIEW

**Comment by dbwiddis** [comment]
I can't get the isCharging boolean to work... convinced it's just not implemented properly anymore.  And the time remaining is inconsistent and useless.  So just the name and % capacity now... 
Sample output: 
Power: InternalBattery-0 @ 96.0%

**Comment by dblock** [comment]
Looks good to me.

**Comment by dbwiddis** [comment]
OK, I've added the windows version and written a Junit test which passes all 3 platforms both plugged-in and on battery.  Ready to merge, with your approval.

**Comment by dbwiddis** [comment]
OK, fixed a few more issues with NPEs (null vs. empty array since Travis CI has no battery) and unsigned 32-bit ints.  Good to merge now, I think!

**Comment by dblock** [comment]
Merged.

**Pull request merged**
