### PR TITLE
Support for processor frequency

### PR DESCRIPTION
**Pull request by alessiofachechi**
Added the `getFreq` and `setFreq` methods to the `Processor` interface and for its implementations for Linux, Windows and Mac.

### CODE REVIEW

**Comment by alessiofachechi** [comment]
@dbwiddis ups, I probably was sleeping when I wrote 1024 instead of 1000! :sweat_smile: 
Anyway yes, it should be better to rename the `getFreq` and `setFreq` in `getMaxFreq` and `setMaxFreq`. I will do this soon!
Thanks for your time! :smiley:

**Comment by dbwiddis** [comment]
I hope you're still working on this.  I'm looking into making a 1.2 release and would be great if we can add this first.

If you can merge the latest version here with your version it will help out a lot with your development: you'll see the necessary code to do the sysctl() calls on Mac OS X, and the frequency one should be an easy copy/paste from the other examples.  Also for windows, the PowrProf library and method has been added so you'd just need to add the new informationlevel (11) and structure.  See the new PowerSupply code for example and see https://msdn.microsoft.com/en-us/library/windows/desktop/aa372675(v=vs.85).aspx for more details.

Also squashing your commits will make it easier to review!

**Comment by alessiofachechi** [comment]
Yeah @dbwiddis, sure. I will fix  this weekend and improve with your advices the code (sorry again for the bug, I coded it very fastly for a project I work on).

**Comment by alessiofachechi** [comment]
Hi @dbwiddis, did you notice that last upstream commits are not 1.5 compatible?

**Comment by dbwiddis** [comment]
Nobody uses 1.5 anymore:  https://plumbr.eu/blog/java/java-version-statistics-2015-edition

Java 1.6 reached end of supported life in February 2013.  I personally don't find any compelling reason to code for anything earlier than 1.7 (which itself has just reached end of supported life but is still widely used), and have not seen anything in the project documentation to constrain me otherwise.  

All that said... what did I use that's post 1.5?  If it's an easy change to make I'll consider it, but most open source projects I work with have already announced 1.7+.

@dblock may want to weigh in on this.

**Comment by dbwiddis** [comment]
I think the 1.7 dependency is the File.readallbytes()... there are ways to do that in older versions if we want to support pre-1.7, I suppose.  Do we?

**Comment by dblock** [comment]
I think we can stop with 1.5 at this point :)

**Comment by dbwiddis** [comment]
How about 1.6, then?   I can easily replace the Files.readAllBytes() call with the exact same source code the Java 7 version calls.  So this is less about this particular change as what policy we want to set moving forward.

**Comment by alessiofachechi** [comment]
Ehm... I use 1.5 for the project I work on ahah! Joking aside it's because I saw in pom.xml:
```
<maven.compiler.source>1.5</maven.compiler.source>
<maven.compiler.target>1.5</maven.compiler.target>
```

**Comment by dbwiddis** [comment]
So I went to try to compile under 1.5 and it's not complaining about readAllBytes(), possibly because the underlying source code doesn't do anything crazy ... the main incompatibility seems to be using @Override on methods implementing an interface.  Which appears to be a 1.6 thing (and Eclipse adds it for me automatically.)

**Comment by alessiofachechi** [comment]
Yes, exactly. Also `FormatUtilTest` needs to be fixed changing
```
@BeforeClass
public static void setUpClass() {
	// use decimal separator according to current locale
	DECIMAL_SEPARATOR = DecimalFormatSymbols.getInstance().getDecimalSeparator();
}
```
with 
```
@BeforeClass
public static void setUpClass() {
	// use decimal separator according to current locale
	DecimalFormatSymbols syms = new DecimalFormatSymbols();
	DecimalFormatSymbols syms = new DecimalFormatSymbols();
}
```

**Comment by alessiofachechi** [comment]
Yes, if you configure the project to be 1.6 compliant Eclipse adds them for you. Probably it's because you have not configured the project as a Maven project. In the latter case Eclipse should read the target from the pom.xml.

**Comment by dbwiddis** [comment]
Aha.... and once Maven's properly configured it's complaining about that readAllBytes().   So, @dblock, do you want 1.6 or 1.7?

**Comment by alessiofachechi** [comment]
If there's no big effort I'd suggest to keep 1.5 compliance (removing bad `@Override`s, etc).

**Comment by dbwiddis** [comment]
`@Override`s aren't bad!  That's why they're included in less ancient versions!  :smirk:

But the point is taken.  I've removed them and replaced the `readAllBytes()` method with the code that method actually executes in Java 7 (and your suggested change to FormatUtilTest.)

**Comment by alessiofachechi** [comment]
`@Override` should be applied when you override a method behaviour, not when you implement an interface method... But hey, that's only phylosophy! :stuck_out_tongue_winking_eye:

**Comment by dblock** [comment]
So 1.5 compat is fixed in https://github.com/dblock/oshi/pull/33 (thanks), what do we do with this PR?

**Comment by alessiofachechi** [comment]
I think it's better if I close this PR, refork the project, rebase my local changes to the upstream and then redo a cleaner PR when I'll complete them. Is it?

**Comment by dbwiddis** [comment]
@alessiofachechi: another philosophy is to use `@Override` whenever possible to avoid mistakes with misspellings or incorrect method signatures (e.g., using a more specific type than the interface).  Personally, I have no philosophy, only an assumption that a newer version of Java/my IDE is probably much wiser than I am.  What we really needs is an `@Implements` annotation!  Maybe that'll come in Java 9.

I think if you merge upstream, rebase, and then reorder the commits to put the merge first, and then squash everything else to a second commit, you get the same effect as your suggestion (which was my default choice on two earlier PRs as I was still learning git.)

**Comment by dblock** [comment]
@alessiofachechi You can always do this:

```
git checkout master
git checkout -b save-my-code # creates a new branch from your current master
git reset --hard HEAD~10 # rewind 10 commits
git pull upstream master # sync with upstream master
git push origin master -f # force push master
git checkout -b my-new-topic-branch
git merge save-my-code --squash
```

**Comment by alessiofachechi** [comment]
Thanks to both! :)

**Comment by dbwiddis** [comment]
Travis CI build is failing on `testCpuVendorFreq()` in `oshi.SystemInfoTest`.  It may be the vendor string doesn't return a parseable Hz value.

**Comment by dbwiddis** [comment]
While you're making minor edits, can you add OS X 10.11 "El Capitan" ? :grin:

**Comment by alessiofachechi** [comment]
Yes @dbwiddis, it was because of a not parseable Hz value (I'd like to know the CPU name string of the Travis machine :smile:).

Anyway I coded the `ParseUtil` class as you suggested to avoid code repetition.

**Comment by dbwiddis** [comment]
Looks great.  Add an entry to the CHANGELOG and we're all set!

**Comment by alessiofachechi** [comment]
Done! :)

**Comment by alessiofachechi** [comment]
Next is

**Comment by alessiofachechi** [comment]
Next feature will be, as you suggested, che current proc freq. :)

**Comment by dbwiddis** [comment]
Take a look at Issue #28 before working on current freq.  Many of the elements currently in the Processor class are for the entire machine, while some (current frequency, and potentially CPU usage) can be measured per-virtual processor.  I'd like to develop a more consistent way of displaying that (similar to how I did the power sources with overall summary (state, time left) and individual (percent capacity).

**Comment by alessiofachechi** [comment]
Perfect! I'd like to contribute when possible also in revising the library architecture if you need! :)

**Comment by dbwiddis** [comment]
Please do. If you have a strong opinion, take charge.  I haven't even started because I'm mulling over a naming convention on just what a Processor or CPU or Core is these days!

**Pull request merged**
