### PR TITLE
Add uptime capability. #73

### PR DESCRIPTION
**Pull request by dbwiddis**

### CODE REVIEW

**Comment by dbwiddis** [comment]
Travis is failing because JAVA_HOME is not defined correctly... no idea how to fix that!

**Comment by dbwiddis** [comment]
OK, seems a relatively new thing that Travis CI has implemented OS X support.  Previously our builds were only running against Linux.

But OS X needs JAVA_HOME set and I don't know what to set it to for the travis VM.

We can allow errors in travis.yml on OS X for the time being, while this gets resolved...

**Comment by dblock** [comment]
You can set the env variables in Travis via `env:`, http://docs.travis-ci.com/user/environment-variables. So figure out what JAVA_HOME should be and just hard-code it in there?

**Comment by dblock** [comment]
Note that Travis claims that JAVA_HOME is correctly set in http://docs.travis-ci.com/user/environment-variables/. Maybe it's a bug in their infrastructure?

**Pull request merged**
